services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    environment:
      NODE_ENV: development
      REDIS_HOST: redis://redis:6379
    ports:
      - "${PORT}:9000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - redis
    networks:
      - elrecord_network

  redis:
    image: redis:7-alpine
    container_name: redis-elrecord-dev
    ports:
      - "6379:6379"
    networks:
      - elrecord_network

networks:
  elrecord_network:
    driver: bridge
